language: node_js
node_js: '5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - gulp remote:$TEST
sudo: false
cache:
  directories:
    - node_modules
env:
  matrix:
    - CXX=g++-4.8 TEST=mac-chrome-latest
    - CXX=g++-4.8 TEST=mac-firefox-latest
    - CXX=g++-4.8 TEST=mac-safari-latest
    - CXX=g++-4.8 TEST=windows-chrome-latest
    - CXX=g++-4.8 TEST=windows-firefox-latest
    - CXX=g++-4.8 TEST=windows-microsoftedge-latest
    - CXX=g++-4.8 TEST=windows-ie-latest
    - CXX=g++-4.8 TEST=linux-chrome-latest
    - CXX=g++-4.8 TEST=linux-firefox-latest
    - CXX=g++-4.8 TEST=ios-latest
    - CXX=g++-4.8 TEST=android-latest
