language: node_js
node_js: '0.10'
script:
  - grunt karma:$SAUCE_BROWSER
before_install:
  - npm install -g grunt-cli
before_script:
  - grunt:build
  - grunt:server &
branches:
  only:
    - master
    - develop
    - /^sauce-.+$/
    - /^v\d+\.\d+\.\d+$/
env:
  global:
    - secure: "Smk4w36atd3Ttj0XsoEZr6dMplTWsK52E70EpxTV72hTQIYa3w5uHMEKpg/sZ9ZFfYQF7Rx003Dmbq9AUGPxqlgPtE8CFWlqYBRAVmvQHTEHmhzIKe0NJ8cXtWWVLnnqbsd9vanXGhd8jjC65ZJYQfOVsbPMShVwv2bSLcTr0cE="
    - secure: "Mgrp2KtzPaZIG36ZoKleP2WneOamT5WFIFUDhS0mj4jbAFSjXWGnRJI7R0XuT9wDmS/f0gIsxazFELXher9CAmsa3VINFW3cVztykqIMSD5HBhyOyTuVzi6q3tvhx2u/OCxqV8o12XrgGJnKwnBuHbapHqhM39CJI2UjYhsgct8="
  matrix:
    - SAUCE_BROWSER=remote-mac-chrome
    - SAUCE_BROWSER=remote-mac-firefox
    - SAUCE_BROWSER=remote-mac-safari
    - SAUCE_BROWSER=remote-windows-chrome
    - SAUCE_BROWSER=remote-windows-firefox
    - SAUCE_BROWSER=remote-windows-ie-11
    - SAUCE_BROWSER=remote-windows-ie-10
    - SAUCE_BROWSER=remote-windows-ie-9
    - SAUCE_BROWSER=remote-linux-chrome
    - SAUCE_BROWSER=remote-linux-firefox
    - SAUCE_BROWSER=remote-ipad
    - SAUCE_BROWSER=remote-iphone
    - SAUCE_BROWSER=remote-android
