name: Quill - Your powerful rich text editor
description: Quill is a free, open source WYSIWYG editor built for the modern web. Completely customize it for any need with its modular architecture and expressive API.
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
version: 1.3.6
cdn: //cdn.quilljs.com/
github: https://github.com/quilljs/quill/tree/develop/docs
quill: quill.min.js
highlightjs: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0
katex: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1
url: https://quilljs.com
