name: Quill - Your powerful, rich text editor
description: Quill is a free, open source WYSIWYG editor built for the modern web. With its modular architecture and expressive API, it is completely customizable to fit any need.
timezone: America/Los_Angeles
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
version: 1.1.9
cdn: //cdn.quilljs.com/
github: https://github.com/quilljs/quill/tree/develop/docs
quill: quill.min.js
highlightjs: //cdnjs.cloudflare.com/ajax/libs/highlight.js/9.3.0
katex: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0
url: https://quilljs.com
